name: go test

on:
  push:
    paths: backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "./backend/go.mod"
          cache-dependency-path: "./backend/go.sum"
      - name: Test
        run: |
          cd backend
          go test -exec sudo -v ./...
